apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablogonzalezr001/git-helm-k8-argcd.git'
    path: k8s/overlays/staging
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
