server:
  port: 9000

spring:
  application:
    name: ai-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
